pheno_features_of_interest <- c("age_at_initial_pathologic_diagnosis",
  "breslow_depth_value",
  "days_to_collection.samples",
  "days_to_submitted_specimen_dx",
  "gender.demographic",
  "height.exposures",
  "history_of_neoadjuvant_treatment",
  "icd_10_code.diagnoses",
  "initial_weight.samples",
  "malignant_neoplasm_mitotic_count_rate",
  "melanoma_clark_level_value",
  "melanoma_ulceration_indicator",
  "pathologic_M",
  "pathologic_N",
  "pathologic_T",
  "primary_diagnosis.diagnoses",
  "prior_malignancy.diagnoses",
  "prior_systemic_therapy_type", #NA = None
  "race.demographic",
  "ethnicity.demographic",
  "site_of_resection_or_biopsy.diagnoses",
  "submitted_tumor_location",
  "system_version",
  "weight")
